version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"  # Cambia el puerto 9000 a otro si lo necesitas
    volumes:
      - .:/var/www/html